apiVersion: v1
kind: Secret
metadata:
  name: secret
  labels:
    app: ${project.artifactId}
stringData:
  some.secret.data: "keep this a secret!"
  service.map.data: >
    key1 : val1 |
    key2 : val2 |
    key3 : val3